
name: SonarQube Scan
on:
  push:
    branches:
      - main
env:
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ env.GITHUB_SHA }}
        repository: ${{ env.GITHUB_REPOSITORY }}
        path: repository

    - name: Set up JDK
      uses: actions/setup-java@v3.10.0
      with:
        java-version: 11.0.18+10
        distribution: temurin
    #- name: Set up JDK
     # uses: actions/setup-java@v3.10.0
      #with:
      #  java-version: 1.8

    - name: Scan with SonarQube
      uses: SonarSource/sonarqube-scan-action@v1.2.0
      with:
        sonar-token: ${{ env.SONAR_TOKEN }}
        repository-path: repository
